# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SLT_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1555, 851)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainWidget = QtWidgets.QWidget(self.centralwidget)
        self.MainWidget.setGeometry(QtCore.QRect(30, 30, 1031, 751))
        self.MainWidget.setStyleSheet("background-color:rgb(229, 229, 229);\n"
"border-color: rgb(0, 0, 0);\n"
"\n"
"border-top-left-radius:50px;\n"
"border-top-right-radius:50px;\n"
"border-bottom-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.MainWidget.setObjectName("MainWidget")
        self.exitButton = QtWidgets.QPushButton(self.MainWidget)
        self.exitButton.setGeometry(QtCore.QRect(960, 0, 71, 61))
        self.exitButton.setStyleSheet("background-color:rgb(128, 163, 0);\n"
"color: white; \n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:50px;\n"
"border-bottom-left-radius:20px;\n"
"border-bottom-right-radius:5px;\n"
"border-color:rgb(166, 166, 166);\n"
"border: 2px groove gray;\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"border-top:none;\n"
"border-right:none;\n"
"\n"
"")
        self.exitButton.setObjectName("exitButton")
        self.gridFrame = QtWidgets.QFrame(self.MainWidget)
        self.gridFrame.setGeometry(QtCore.QRect(110, 90, 871, 601))
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.startSpeechToText = QtWidgets.QPushButton(self.gridFrame)
        self.startSpeechToText.setStyleSheet("background-color: rgb(47, 79, 144);\n"
"color: white; \n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.startSpeechToText.setObjectName("startSpeechToText")
        self.gridLayout.addWidget(self.startSpeechToText, 3, 2, 2, 1)
        self.hearingAblePersonText = QtWidgets.QLabel(self.gridFrame)
        self.hearingAblePersonText.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"border-color:rgb(217, 25, 92);\n"
"\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;")
        self.hearingAblePersonText.setText("")
        self.hearingAblePersonText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hearingAblePersonText.setWordWrap(True)
        self.hearingAblePersonText.setObjectName("hearingAblePersonText")
        self.gridLayout.addWidget(self.hearingAblePersonText, 3, 1, 2, 1)
        self.startTranslation = QtWidgets.QPushButton(self.gridFrame)
        self.startTranslation.setStyleSheet("background-color: rgb(217, 64, 117);\n"
"color: white; \n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.startTranslation.setObjectName("startTranslation")
        self.gridLayout.addWidget(self.startTranslation, 1, 0, 1, 1)
        self.stopTranslation = QtWidgets.QPushButton(self.gridFrame)
        self.stopTranslation.setStyleSheet("background-color:rgb(47, 79, 144);\n"
"color: white; \n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.stopTranslation.setObjectName("stopTranslation")
        self.gridLayout.addWidget(self.stopTranslation, 2, 0, 1, 1)
        self.webCam = QtWidgets.QLabel(self.gridFrame)
        self.webCam.setMinimumSize(QtCore.QSize(640, 450))
        self.webCam.setStyleSheet("border-style: solid;\n"
"border-width: 10px;\n"
"border-color:rgb(152, 198, 0);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.webCam.setText("")
        self.webCam.setObjectName("webCam")
        self.gridLayout.addWidget(self.webCam, 0, 1, 1, 1)
        self.deafMutePersonText = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deafMutePersonText.sizePolicy().hasHeightForWidth())
        self.deafMutePersonText.setSizePolicy(sizePolicy)
        self.deafMutePersonText.setMinimumSize(QtCore.QSize(0, 50))
        self.deafMutePersonText.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 130, 194);\n"
"\n"
"\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;")
        self.deafMutePersonText.setText("")
        self.deafMutePersonText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.deafMutePersonText.setWordWrap(True)
        self.deafMutePersonText.setObjectName("deafMutePersonText")
        self.gridLayout.addWidget(self.deafMutePersonText, 1, 1, 2, 1)
        self.logo = QtWidgets.QLabel(self.MainWidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 241, 81))
        self.logo.setStyleSheet("border-top-left-radius:50px;\n"
"border-top-right-radius:50px;\n"
"border-bottom-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.MainWidget)
        self.label.setGeometry(QtCore.QRect(930, 720, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridFrame.raise_()
        self.exitButton.raise_()
        self.logo.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign Language Translator"))
        self.exitButton.setText(_translate("MainWindow", "✕"))
        self.startSpeechToText.setText(_translate("MainWindow", "Start"))
        self.startTranslation.setText(_translate("MainWindow", "Start"))
        self.stopTranslation.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Ⓒ AV99"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
